keys:
  - &masonmactest age12cyv0vfpfp5jwdkzgena7df4pg4hj0x83yqdlckl5cxlxaxqgveq9s7d7u 
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        -  *masonmactest
